application:
  title: API Files Service
  version: v1.0

cors:
  allowed:
    originPatterns: http://localhost:8081,http://localhost:3000,http://localhost,http://localhost:8082
    methods: GET,POST,PUT,PATCH,DELETE

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: admin
      password: $2a$10$YgEE0XpMb0vjEbhmNt59UOhk5KTCiIHfaHL2THfPFUhdt8qgxrSOe
  threads:
    virtual:
      enabled: true
  mvc:
    dispatch-trace-request: true
  datasource:
    url: jdbc:mysql://mysql:3306/power_files
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    validate-on-migrate: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: powerpdf
    password: powerpdf
    queue:
      name: pdf_merge_queue
    exchange:
      name: pdf_merge_exchange
    template:
      retry:
        enabled: true
        initial-interval: 5s
        max-interval: 10s
        multiplier: 1.5
    listener:
      direct:
        acknowledge-mode: auto
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 1

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  servlet:
    context-path: /files
  port: 8080


app:
  url: http://localhost
  token: 4pTtiALMXVjDErv3MR5HZxdwDfzO1m2v
  storage:
    url: http://localhost:8082/storage
    bucket: files-bucket
    auth: YWRtaW46JDJhJDEwJFlnRUUwWHBNYjB2akViaG1OdDU5VU9oazVLVENpSUhmYUhMMlRIZlBGVWhkdDhxZ3hyU09l

logging:
  level:
    root: INFO
    com.jfp.files: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/files.log
