DELETE IF EXISTS power_files;

CREATE DATABASE IF NOT EXISTS power_files;

USE power_files;

CREATE TABLE IF NOT EXISTS file_process (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  link VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type_process VARCHAR(50) NOT NULL,
  type_file VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING'
);

CREATE INDEX IF NOT EXISTS idx_file_status ON file_process(status);