application:
  title: API Storage Service
  version: v1.0

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: admin
      password: $2a$10$YgEE0XpMb0vjEbhmNt59UOhk5KTCiIHfaHL2THfPFUhdt8qgxrSOe
  threads:
    virtual:
      enabled: true
  mvc:
    dispatch-trace-request: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

minio:
    url: http://minio:9000
    access-key: minio
    secret-key: minio123
    bucket: files-bucket

server:
  servlet:
    context-path: /storage
  port: 8082

app:
  url: http://localhost
  token: 4pTtiALMXVjDErv3MR5HZxdwDfzO1m2v

logging:
  level:
    root: INFO
    com.jfp.files: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/files.log

