application:
  title: API Uploads
  version: v1.0

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: admin
      password: $2a$10$YgEE0XpMb0vjEbhmNt59UOhk5KTCiIHfaHL2THfPFUhdt8qgxrSOe
  threads:
    virtual:
      enabled: true
  mvc:
    dispatch-trace-request: true

server:
  servlet:
    context-path: /uploads
  port: 8082

app:
  url: http://localhost
  token: 4pTtiALMXVjDErv3MR5HZxdwDfzO1m2v

logging:
  level:
    root: INFO
    com.jfp.uploads: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/uploads.log
