application:
  title: API PDF Service
  version: v1.0

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: admin
      password: $2a$10$YgEE0XpMb0vjEbhmNt59UOhk5KTCiIHfaHL2THfPFUhdt8qgxrSOe
  threads:
    virtual:
      enabled: true
  mvc:
    dispatch-trace-request: true
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/pdf_processing
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    validate-on-migrate: true

server:
  servlet:
    context-path: /uploads
  port: 8082

app:
  url: http://localhost
  token: 4pTtiALMXVjDErv3MR5HZxdwDfzO1m2v

logging:
  level:
    root: INFO
    com.jfp.uploads: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/uploads.log
